replicaCount: 1

image:
  repository: canpolatoral/argocd-test
  tag: latest
  pullPolicy: IfNotPresent

greeting: "Hello, World 2!"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
